from ubuntu:19.10

RUN apt-get update && apt-get install -y \
  build-essential \
  scons \
  valgrind

RUN mkdir /app
RUN mkdir /app/src
WORKDIR /app/src

COPY ./SimpleServ/app/*.h /app/src/app/
COPY ./SimpleServ/app/*.cpp /app/src/app/
COPY ./SimpleServ/html/*.h /app/src/html/
COPY ./SimpleServ/html/*.cpp /app/src/html/
COPY ./SimpleServ/http/*.h /app/src/http/
COPY ./SimpleServ/http/*.cpp /app/src/http/
COPY ./SimpleServ/tcp/*.h /app/src/tcp/
COPY ./SimpleServ/tcp/*.cpp /app/src/tcp/
COPY ./SimpleServ/test/html/*.h /app/src/test/html/
COPY ./SimpleServ/test/html/*.cpp /app/src/test/html/
COPY ./SimpleServ/test/test.cpp /app/src/test/
COPY ./SimpleServ/SConstruct /app/src

RUN scons -Q test=1 && scons -Q test=1 -c

RUN cp /app/src/build/tests /app
RUN rm -rf /app/src

WORKDIR /app

CMD [ "valgrind", "/app/tests" ]
