#include "HttpStatus.h"

namespace Http {
	std::map<StatusCode, std::string> StatusDescriptions::_descriptions = {
		{ StatusCode_Continue, "Continue" },
		{ StatusCode_SwitchingProtocols, "Switching Protocols" },
		{ StatusCode_OK, "OK" },
		{ StatusCode_Created, "Created" },
		{ StatusCode_Accepted, "Accepted" },
		{ StatusCode_NonAuthoritativeInformation, "Non-Authoritative Information" },
		{ StatusCode_NoContent, "No Content" },
		{ StatusCode_ResetContent, "Reset Content" },
		{ StatusCode_PartialContent, "Partial Content" },
		{ StatusCode_MultiStatus, "Multi-Status" },
		{ StatusCode_AlreadyReported, "Already Reported " },
		{ StatusCode_IMUsed, "IM Used " },
		{ StatusCode_MultipleChoices, "Multiple Choices" },
		{ StatusCode_MovedPermanently, "Moved Permanently" },
		{ StatusCode_Found, "Found" },
		{ StatusCode_SeeOther, "See Other" },
		{ StatusCode_NotModified, "Not Modified " },
		{ StatusCode_UseProxy, "Use Proxy " },
		{ StatusCode_SwitchProxy, "Switch Proxy" },
		{ StatusCode_TemporaryRedirect, "Temporary Redirect " },
		{ StatusCode_PermanentRedirect, "Permanent Redirect " },
		{ StatusCode_ResumeIncomplete, "Resume Incomplete " },
		{ StatusCode_BadRequest, "Bad Request" },
		{ StatusCode_Unauthorized, "Unauthorized " },
		{ StatusCode_PaymentRequired, "Payment Required" },
		{ StatusCode_Forbidden, "Forbidden" },
		{ StatusCode_NotFound, "Not Found" },
		{ StatusCode_MethodNotAllowed, "Method Not Allowed" },
		{ StatusCode_NotAcceptable, "Not Acceptable" },
		{ StatusCode_ProxyAuthenticationRequired, "Proxy Authentication Required" },
		{ StatusCode_RequestTimeout, "Request Timeout" },
		{ StatusCode_Conflict, "Conflict" },
		{ StatusCode_Gone, "Gone" },
		{ StatusCode_LengthRequired, "Length Required" },
		{ StatusCode_PreconditionFailed, "Precondition Failed" },
		{ StatusCode_RequestEntityTooLarge, "Request Entity Too Large" },
		{ StatusCode_RequestURITooLong, "Request-URI Too Long" },
		{ StatusCode_UnsupportedMediaType, "Unsupported Media Type" },
		{ StatusCode_RequestedRangeNotSatisfiable, "Requested Range Not Satisfiable" },
		{ StatusCode_ExpectationFailed, "Expectation Failed" },
		{ StatusCode_Imateapot, "I'm a teapot" },
		{ StatusCode_AuthenticationTimeout, "Authentication Timeout" },
		{ StatusCode_MethodFailure, "Method Failure" },
		{ StatusCode_EnhanceYourCalm, "Enhance Your Calm" },
		{ StatusCode_MisdirectedRequest, "Misdirected Request" },
		{ StatusCode_UnprocessableEntity, "Unprocessable Entity" },
		{ StatusCode_Locked, "Locked" },
		{ StatusCode_FailedDependency, "Failed Dependency " },
		{ StatusCode_UpgradeRequired, "Upgrade Required" },
		{ StatusCode_PreconditionRequired, "Precondition Required " },
		{ StatusCode_TooManyRequests, "Too Many Requests" },
		{ StatusCode_RequestHeaderFieldsTooLarge, "Request Header Fields Too Large " },
		{ StatusCode_UnavailableForLegalReasons, "Unavailable For Legal Reasons " },
		{ StatusCode_InternalServerError, "Internal Server Error" },
		{ StatusCode_NotImplemented, "Not Implemented" },
		{ StatusCode_BadGateway, "Bad Gateway" },
		{ StatusCode_ServiceUnavailable, "Service Unavailable" },
		{ StatusCode_GatewayTimeout, "Gateway Timeout" },
		{ StatusCode_HTTPVersionNotSupported, "HTTP Version Not Supported" },
		{ StatusCode_NotExtended, "Not Extended" },
		{ StatusCode_NetworkAuthenticationRequired, "Network Authentication Required" },
	};
}