import os
env=Environment(CPPPATH='.',
                CPPDEFINES=[],
                LIBS=[],
                CXXFLAGS="-std=c++2a"
                )
                
files = Glob('*.cpp')
env.Program("build/SimpleServ", files)
